# ==============================================================================
# Merged Lakeflow Source: dynamics_business_central
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/sources/dynamics_business_central/dynamics_business_central_schemas.py
    ########################################################

    RETRIABLE_STATUS_CODES = {429, 500, 503}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0

    TOKEN_SCOPE = "https://api.businesscentral.dynamics.com/.default"
    TOKEN_URL_TEMPLATE = "https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token"
    BASE_URL_TEMPLATE = (
        "https://api.businesscentral.dynamics.com/v2.0/{tenant_id}/{environment}"
    )

    LOOKBACK_SECONDS = 60

    # --- Table registry -----------------------------------------------------------
    # Each entry maps a table name (= entitySetName) to its metadata.
    #   api_group: the URL segment after /api/databricks/
    #   company_scoped: whether the endpoint requires /companies({cid})/
    #   ingestion_type: snapshot | cdc | cdc_with_deletes | append
    #   cursor_field: field used for incremental reads
    #   primary_keys: list of PK field names
    #   bc_table_id: Business Central internal table ID (for delete tracking)

    TABLE_REGISTRY: dict[str, dict] = {
        # -- metadata group (not company-scoped) -----------------------------------
        "pageMetadata": {
            "api_group": "metadata",
            "company_scoped": True,
            "ingestion_type": "snapshot",
            "cursor_field": None,
            "primary_keys": ["id"],
            "bc_table_id": None,
        },
        "tableMetadata": {
            "api_group": "metadata",
            "company_scoped": True,
            "ingestion_type": "snapshot",
            "cursor_field": None,
            "primary_keys": ["id"],
            "bc_table_id": None,
        },
        # -- standard endpoints: cdc_with_deletes ----------------------------------
        "generalLedgerAccounts": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 15,
        },
        "bankAccounts": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 270,
        },
        "companyInformation": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "contacts": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 5050,
        },
        "countriesRegions": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 9,
        },
        "currencies": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 4,
        },
        "currencyExchangeRates": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 330,
        },
        "customers": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 18,
        },
        "generalJournalBatches": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 232,
        },
        "reasonCodes": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 231,
        },
        "generalJournalLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 81,
        },
        "defaultDimensions": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 352,
        },
        "dimensionValues": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 349,
        },
        "dimensions": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 348,
        },
        "employees": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 5200,
        },
        "generalProductPostingGroups": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 251,
        },
        "vendors": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 23,
        },
        "inventoryPostingGroups": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 94,
        },
        "itemCategories": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 5722,
        },
        "itemVariants": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 5401,
        },
        "items": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 27,
        },
        "locations": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 14,
        },
        "opportunities": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 5092,
        },
        "paymentMethods": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 289,
        },
        "paymentTerms": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 3,
        },
        "purchaseLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 39,
        },
        "jobs": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 167,
        },
        "shipmentMethods": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 10,
        },
        "unitsOfMeasure": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 204,
        },
        "timeSheetDetails": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 953,
        },
        "salesHeaders": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 36,
        },
        "salesLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 37,
        },
        "purchaseHeaders": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "cdc_with_deletes",
            "cursor_field": "systemModifiedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": 38,
        },
        # -- standard endpoints: append (posted/immutable) -------------------------
        "generalLedgerEntries": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "itemLedgerEntries": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "purchaseReceiptLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "salesCreditMemoLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "purchaseReceiptHeaders": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "salesCreditMemoHeaders": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "salesShipmentLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "salesShipmentHeaders": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "postedGeneralJournalBatch": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "postedGeneralJournalLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "purchaseInvoiceHeaders": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "purchaseInvoiceLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "salesInvoiceHeaders": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "salesInvoiceLines": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "append",
            "cursor_field": "systemCreatedAt",
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        # -- standard endpoints: snapshot ------------------------------------------
        "rawCompanies": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "snapshot",
            "cursor_field": None,
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
        "dimensionSetEntries": {
            "api_group": "standardEndpoints",
            "company_scoped": True,
            "ingestion_type": "snapshot",
            "cursor_field": None,
            "primary_keys": ["systemId"],
            "bc_table_id": None,
        },
    }

    # OData EDM type -> Spark type mapping used for dynamic schema discovery
    EDM_TYPE_MAP: dict[str, type] = {
        "Edm.String": StringType,
        "Edm.Guid": StringType,
        "Edm.Int32": LongType,
        "Edm.Int64": LongType,
        "Edm.Decimal": DecimalType,
        "Edm.Double": DecimalType,
        "Edm.Boolean": BooleanType,
        "Edm.Date": StringType,
        "Edm.DateTimeOffset": StringType,
        "Edm.Duration": StringType,
        "Edm.Stream": StringType,
        "Edm.Binary": StringType,
    }

    # Delete tracking schema (for the deletedRecords API page)
    DELETED_RECORD_SCHEMA = StructType([
        StructField("entryNo", LongType(), nullable=False),
        StructField("tableId", LongType(), nullable=True),
        StructField("companyId", StringType(), nullable=True),
        StructField("deletedSystemId", StringType(), nullable=True),
        StructField("recordPosition", StringType(), nullable=True),
        StructField("deletedAt", StringType(), nullable=True),
        StructField("systemModifiedAtOriginal", StringType(), nullable=True),
        StructField("systemCreatedAt", StringType(), nullable=True),
        StructField("systemCreatedBy", StringType(), nullable=True),
        StructField("systemId", StringType(), nullable=True),
        StructField("systemModifiedAt", StringType(), nullable=True),
        StructField("systemModifiedBy", StringType(), nullable=True),
    ])

    DELETE_TRACKER_SCHEMA = StructType([
        StructField("id", StringType(), nullable=True),
        StructField("tableId", LongType(), nullable=True),
        StructField("companyId", StringType(), nullable=True),
        StructField("recordsDeleted", LongType(), nullable=True),
        StructField("systemCreatedAt", StringType(), nullable=True),
        StructField("systemModifiedAt", StringType(), nullable=True),
        StructField("systemId", StringType(), nullable=True),
    ])


    ########################################################
    # src/databricks/labs/community_connector/sources/dynamics_business_central/dynamics_business_central.py
    ########################################################

    class DynamicsBusinessCentralLakeflowConnect(LakeflowConnect):

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._tenant_id = options["tenant_id"]
            self._client_id = options["client_id"]
            self._client_secret = options["client_secret"]
            self._environment = options["environment"]
            self._company_id = options["company_id"]

            self._base_url = BASE_URL_TEMPLATE.format(
                tenant_id=self._tenant_id, environment=self._environment
            )
            self._access_token: str | None = None
            self._token_expires_at: float = 0.0

            self._init_ts = self._to_utc_z(datetime.now(timezone.utc))
            self._lookback_applied_tables: set[str] = set()

            self._schema_cache: dict[str, StructType] = {}

        # ── DateTime helpers ───────────────────────────────────────────────────

        @staticmethod
        def _to_utc_z(dt: datetime) -> str:
            """Format a datetime as ISO 8601 with Z suffix for BC OData compatibility."""
            if dt.tzinfo is not None:
                dt = dt.astimezone(timezone.utc)
            return dt.strftime("%Y-%m-%dT%H:%M:%S.%fZ")

        @staticmethod
        def _parse_dt(value: str) -> datetime:
            """Parse an ISO 8601 string, normalising both Z and +00:00 suffixes."""
            if value.endswith("Z"):
                value = value[:-1] + "+00:00"
            return datetime.fromisoformat(value)

        def _dt_gte(self, a: str, b: str) -> bool:
            """Semantically compare two ISO 8601 strings (a >= b)."""
            return self._parse_dt(a) >= self._parse_dt(b)

        # ── Authentication ────────────────────────────────────────────────────

        def _ensure_token(self) -> str:
            if self._access_token and time.time() < self._token_expires_at - 60:
                return self._access_token

            token_url = TOKEN_URL_TEMPLATE.format(tenant_id=self._tenant_id)
            body = urllib.parse.urlencode({
                "grant_type": "client_credentials",
                "client_id": self._client_id,
                "client_secret": self._client_secret,
                "scope": TOKEN_SCOPE,
            }).encode()

            req = urllib.request.Request(token_url, data=body, method="POST")
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read())

            self._access_token = data["access_token"]
            self._token_expires_at = time.time() + int(data.get("expires_in", 3600))
            return self._access_token

        # ── HTTP helpers ──────────────────────────────────────────────────────

        def _api_get(self, url: str) -> dict:
            """GET with retries and exponential backoff on transient errors."""
            token = self._ensure_token()
            backoff = INITIAL_BACKOFF
            last_error = None

            for attempt in range(MAX_RETRIES):
                req = urllib.request.Request(url, headers={
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/json",
                })
                try:
                    with urllib.request.urlopen(req, timeout=60) as resp:
                        return json.loads(resp.read())
                except urllib.error.HTTPError as e:
                    last_error = e
                    if e.code == 401:
                        self._access_token = None
                        token = self._ensure_token()
                        continue
                    if e.code in RETRIABLE_STATUS_CODES:
                        retry_after = e.headers.get("Retry-After")
                        wait = float(retry_after) if retry_after else backoff
                        if attempt < MAX_RETRIES - 1:
                            time.sleep(wait)
                            backoff *= 2
                        continue
                    raise RuntimeError(
                        f"API request failed: HTTP {e.code} for {url}: "
                        f"{e.read().decode()[:500]}"
                    ) from e
                except urllib.error.URLError as e:
                    last_error = e
                    if attempt < MAX_RETRIES - 1:
                        time.sleep(backoff)
                        backoff *= 2
                        continue
                    raise

            raise RuntimeError(
                f"API request failed after {MAX_RETRIES} retries: {last_error}"
            )

        def _api_post(self, url: str, payload: dict) -> dict:
            token = self._ensure_token()
            data = json.dumps(payload).encode()
            req = urllib.request.Request(url, data=data, method="POST", headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/json",
                "Content-Type": "application/json",
            })
            try:
                with urllib.request.urlopen(req, timeout=30) as resp:
                    return json.loads(resp.read())
            except urllib.error.HTTPError as e:
                raise RuntimeError(
                    f"POST failed: HTTP {e.code} for {url}: "
                    f"{e.read().decode()[:500]}"
                ) from e

        def _build_url(self, table_name: str) -> str:
            meta = TABLE_REGISTRY[table_name]
            group = meta["api_group"]
            if meta["company_scoped"]:
                return (
                    f"{self._base_url}/api/databricks/{group}/v1.0"
                    f"/companies({self._company_id})/{table_name}"
                )
            return f"{self._base_url}/api/databricks/{group}/v1.0/{table_name}"

        def _build_delete_tracking_url(self, entity: str) -> str:
            return (
                f"{self._base_url}/api/databricks/deleteTracking/v1.0"
                f"/companies({self._company_id})/{entity}"
            )

        # ── Schema discovery via $metadata ────────────────────────────────────

        def _fetch_edmx_schema(self, api_group: str) -> dict[str, StructType]:
            """Fetch $metadata EDMX and parse entity types into Spark StructTypes.

            Returns a dict keyed by EntitySet name (= entitySetName from AL) so
            callers can look up by table_name directly.
            """
            url = (
                f"{self._base_url}/api/databricks/{api_group}/v1.0/$metadata"
            )
            token = self._ensure_token()
            req = urllib.request.Request(url, headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/xml",
            })
            with urllib.request.urlopen(req, timeout=30) as resp:
                xml_text = resp.read().decode()

            root = ET.fromstring(xml_text)
            ns = {
                "edmx": "http://docs.oasis-open.org/odata/ns/edmx",
                "edm": "http://docs.oasis-open.org/odata/ns/edm",
            }

            type_schemas: dict[str, StructType] = {}
            for entity_type in root.findall(".//edm:EntityType", ns):
                type_name = entity_type.get("Name", "")
                fields: list[StructField] = []
                for prop in entity_type.findall("edm:Property", ns):
                    prop_name = prop.get("Name", "")
                    edm_type = prop.get("Type", "Edm.String")
                    spark_type_cls = EDM_TYPE_MAP.get(edm_type, StringType)
                    if spark_type_cls is DecimalType:
                        spark_type = DecimalType(38, 10)
                    else:
                        spark_type = spark_type_cls()
                    fields.append(StructField(prop_name, spark_type, nullable=True))
                if fields:
                    type_schemas[type_name] = StructType(fields)

            # Build EntitySet name -> EntityType name mapping from the EDMX
            set_to_type: dict[str, str] = {}
            for entity_set in root.findall(".//edm:EntitySet", ns):
                set_name = entity_set.get("Name", "")
                entity_type_ref = entity_set.get("EntityType", "")
                # EntityType is fully qualified, e.g. "Microsoft.NAV.customer"
                short_type = entity_type_ref.rsplit(".", 1)[-1] if "." in entity_type_ref else entity_type_ref
                set_to_type[set_name] = short_type

            # Return keyed by EntitySet name for direct lookup
            schemas: dict[str, StructType] = {}
            for set_name, type_name in set_to_type.items():
                if type_name in type_schemas:
                    schemas[set_name] = type_schemas[type_name]

            return schemas

        def _resolve_schema(self, table_name: str) -> StructType:
            if table_name in self._schema_cache:
                return self._schema_cache[table_name]

            meta = TABLE_REGISTRY[table_name]
            group = meta["api_group"]

            group_schemas = self._fetch_edmx_schema(group)

            matched = group_schemas.get(table_name)
            if matched is None:
                matched = self._infer_schema_from_sample(table_name)

            self._schema_cache[table_name] = matched
            return matched

        def _infer_schema_from_sample(self, table_name: str) -> StructType:
            url = self._build_url(table_name) + "?$top=1"
            data = self._api_get(url)
            records = data.get("value", [])
            if not records:
                raise RuntimeError(
                    f"Cannot infer schema for '{table_name}': no records returned "
                    f"and $metadata matching failed."
                )
            sample = records[0]
            fields = []
            for key, value in sample.items():
                if key.startswith("@odata"):
                    continue
                spark_type = self._guess_spark_type(value)
                fields.append(StructField(key, spark_type, nullable=True))
            return StructType(fields)

        @staticmethod
        def _guess_spark_type(value):
            if isinstance(value, bool):
                return BooleanType()
            if isinstance(value, int):
                return LongType()
            if isinstance(value, float):
                return DecimalType(38, 10)
            return StringType()

        # ── Interface: list_tables ────────────────────────────────────────────

        def list_tables(self) -> list[str]:
            return list(TABLE_REGISTRY.keys())

        # ── Interface: get_table_schema ───────────────────────────────────────

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return self._resolve_schema(table_name)

        # ── Interface: read_table_metadata ────────────────────────────────────

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            meta = TABLE_REGISTRY[table_name]
            result: dict = {
                "ingestion_type": meta["ingestion_type"],
                "primary_keys": meta["primary_keys"],
            }
            if meta["cursor_field"]:
                result["cursor_field"] = meta["cursor_field"]
            return result

        # ── Interface: read_table ─────────────────────────────────────────────

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            meta = TABLE_REGISTRY[table_name]
            ingestion_type = meta["ingestion_type"]

            if ingestion_type == "snapshot":
                return self._read_snapshot(table_name)

            cursor_field = meta["cursor_field"]
            if ingestion_type == "append":
                return self._read_append(
                    table_name, start_offset, table_options, cursor_field
                )
            # cdc and cdc_with_deletes
            return self._read_cdc(
                table_name, start_offset, table_options, cursor_field
            )

        # ── Interface: read_table_deletes ─────────────────────────────────────

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            meta = TABLE_REGISTRY[table_name]
            if meta["ingestion_type"] != "cdc_with_deletes":
                raise ValueError(
                    f"Table '{table_name}' does not support delete tracking "
                    f"(ingestion_type={meta['ingestion_type']})"
                )
            bc_table_id = meta["bc_table_id"]
            if bc_table_id is None:
                raise ValueError(
                    f"Table '{table_name}' has no BC table ID for delete tracking"
                )

            since = start_offset.get("delete_cursor") if start_offset else None
            if since and self._dt_gte(since, self._init_ts):
                return iter([]), start_offset

            max_records = int(table_options.get("max_records_per_batch", "200"))
            base = self._build_delete_tracking_url("deletedRecords")

            filter_parts = [
                f"tableId eq {bc_table_id}",
                f"companyId eq '{self._company_id}'",
            ]
            if since:
                filter_parts.append(f"deletedAt gt {since}")

            filter_str = " and ".join(filter_parts)
            url = f"{base}?$filter={urllib.parse.quote(filter_str)}&$orderby={urllib.parse.quote('deletedAt asc')}"

            records: list[dict] = []
            while len(records) < max_records:
                data = self._api_get(url)
                batch = data.get("value", [])
                if not batch:
                    break

                for rec in batch:
                    records.append({
                        "systemId": rec["deletedSystemId"],
                        "systemModifiedAt": rec["deletedAt"],
                    })
                    if len(records) >= max_records:
                        break

                next_link = data.get("@odata.nextLink")
                if not next_link or len(records) >= max_records:
                    break
                url = next_link

            if not records:
                return iter([]), start_offset or {}

            last_cursor = records[-1]["systemModifiedAt"]
            end_offset = {"delete_cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        # ── Private: read strategies ──────────────────────────────────────────

        def _read_snapshot(
            self, table_name: str
        ) -> tuple[Iterator[dict], dict]:
            url = self._build_url(table_name)
            records: list[dict] = []
            while url:
                data = self._api_get(url)
                for rec in data.get("value", []):
                    records.append(self._strip_odata_fields(rec))
                url = data.get("@odata.nextLink")
            return iter(records), {}

        def _read_cdc(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
            cursor_field: str,
        ) -> tuple[Iterator[dict], dict]:
            """CDC read for cdc and cdc_with_deletes tables. Client-side truncation safe."""
            since = start_offset.get("cursor") if start_offset else None
            if since and self._dt_gte(since, self._init_ts):
                return iter([]), start_offset

            max_records = int(table_options.get("max_records_per_batch", "200"))
            window_seconds = int(table_options.get("window_seconds", "3600"))

            effective_since = since
            if effective_since and table_name not in self._lookback_applied_tables:
                dt = self._parse_dt(effective_since) - timedelta(seconds=LOOKBACK_SECONDS)
                effective_since = self._to_utc_z(dt)
                self._lookback_applied_tables.add(table_name)

            if effective_since:
                window_end_dt = self._parse_dt(effective_since) + timedelta(
                    seconds=window_seconds
                )
                window_end_str = self._to_utc_z(window_end_dt)
                window_end = window_end_str if self._dt_gte(self._init_ts, window_end_str) else self._init_ts
            else:
                window_end = self._init_ts

            url = self._build_filtered_url(
                table_name, cursor_field, effective_since, window_end
            )

            records: list[dict] = []
            while len(records) < max_records:
                data = self._api_get(url)
                batch = data.get("value", [])
                if not batch:
                    break

                for rec in batch:
                    records.append(self._strip_odata_fields(rec))
                    if len(records) >= max_records:
                        break

                next_link = data.get("@odata.nextLink")
                if not next_link or len(records) >= max_records:
                    break
                url = next_link

            if not records:
                end_offset = {"cursor": window_end}
                if start_offset and start_offset == end_offset:
                    return iter([]), start_offset
                return iter([]), end_offset

            last_cursor = records[-1][cursor_field]
            end_offset = {"cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        def _read_append(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
            cursor_field: str,
        ) -> tuple[Iterator[dict], dict]:
            """Append read. No client-side truncation — must process full pages."""
            since = start_offset.get("cursor") if start_offset else None
            if since and self._dt_gte(since, self._init_ts):
                return iter([]), start_offset

            max_records = int(table_options.get("max_records_per_batch", "200"))
            window_seconds = int(table_options.get("window_seconds", "3600"))

            effective_since = since
            if effective_since and table_name not in self._lookback_applied_tables:
                dt = self._parse_dt(effective_since) - timedelta(seconds=LOOKBACK_SECONDS)
                effective_since = self._to_utc_z(dt)
                self._lookback_applied_tables.add(table_name)

            if effective_since:
                window_end_dt = self._parse_dt(effective_since) + timedelta(
                    seconds=window_seconds
                )
                window_end_str = self._to_utc_z(window_end_dt)
                window_end = window_end_str if self._dt_gte(self._init_ts, window_end_str) else self._init_ts
            else:
                window_end = self._init_ts

            url = self._build_filtered_url(
                table_name, cursor_field, effective_since, window_end
            )

            records: list[dict] = []
            while True:
                data = self._api_get(url)
                batch = data.get("value", [])
                if not batch:
                    break

                for rec in batch:
                    records.append(self._strip_odata_fields(rec))

                next_link = data.get("@odata.nextLink")
                if not next_link:
                    break
                if len(records) >= max_records:
                    break
                url = next_link

            if not records:
                end_offset = {"cursor": window_end}
                if start_offset and start_offset == end_offset:
                    return iter([]), start_offset
                return iter([]), end_offset

            last_cursor = records[-1][cursor_field]
            end_offset = {"cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        # ── URL building ──────────────────────────────────────────────────────

        def _build_filtered_url(
            self,
            table_name: str,
            cursor_field: str,
            since: str | None,
            until: str | None,
        ) -> str:
            base = self._build_url(table_name)
            filter_parts = []
            if since:
                filter_parts.append(f"{cursor_field} gt {since}")
            if until:
                filter_parts.append(f"{cursor_field} le {until}")

            params = {}
            if filter_parts:
                params["$filter"] = " and ".join(filter_parts)
            params["$orderby"] = f"{cursor_field} asc"

            return base + "?" + urllib.parse.urlencode(params, quote_via=urllib.parse.quote)

        # ── Delete tracker registration ───────────────────────────────────────

        def ensure_delete_trackers(self) -> None:
            """Register delete trackers for all cdc_with_deletes tables.

            Call this once after deployment to ensure the event handler captures
            deletes for the tables this connector cares about.
            """
            tracker_url = self._build_delete_tracking_url("deleteTrackers")

            existing = set()
            url = tracker_url
            while url:
                data = self._api_get(url)
                for rec in data.get("value", []):
                    existing.add((rec["tableId"], rec["companyId"]))
                url = data.get("@odata.nextLink")

            for table_name, meta in TABLE_REGISTRY.items():
                if meta["ingestion_type"] != "cdc_with_deletes":
                    continue
                bc_id = meta.get("bc_table_id")
                if bc_id is None:
                    continue
                key = (bc_id, self._company_id)
                if key not in existing:
                    self._api_post(tracker_url, {
                        "tableId": bc_id,
                        "companyId": self._company_id,
                    })

        # ── Helpers ───────────────────────────────────────────────────────────

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLE_REGISTRY:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {list(TABLE_REGISTRY.keys())}"
                )

        @staticmethod
        def _strip_odata_fields(record: dict) -> dict:
            return {k: v for k, v in record.items() if not k.startswith("@odata")}


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = DynamicsBusinessCentralLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
