"""Schemas, metadata, and constants for the Dynamics 365 Business Central connector."""

from pyspark.sql.types import (
    BooleanType,
    DecimalType,
    LongType,
    StringType,
    StructField,
    StructType,
)

RETRIABLE_STATUS_CODES = {429, 500, 503}
MAX_RETRIES = 5
INITIAL_BACKOFF = 1.0

TOKEN_SCOPE = "https://api.businesscentral.dynamics.com/.default"
TOKEN_URL_TEMPLATE = "https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token"
BASE_URL_TEMPLATE = (
    "https://api.businesscentral.dynamics.com/v2.0/{tenant_id}/{environment}"
)

LOOKBACK_SECONDS = 60

# --- Table registry -----------------------------------------------------------
# Each entry maps a table name (= entitySetName) to its metadata.
#   api_group: the URL segment after /api/databricks/
#   company_scoped: whether the endpoint requires /companies({cid})/
#   ingestion_type: snapshot | cdc | cdc_with_deletes | append
#   cursor_field: field used for incremental reads
#   primary_keys: list of PK field names
#   bc_table_id: Business Central internal table ID (for delete tracking)

TABLE_REGISTRY: dict[str, dict] = {
    # -- metadata group (not company-scoped) -----------------------------------
    "pageMetadata": {
        "api_group": "metadata",
        "company_scoped": True,
        "ingestion_type": "snapshot",
        "cursor_field": None,
        "primary_keys": ["id"],
        "bc_table_id": None,
    },
    "tableMetadata": {
        "api_group": "metadata",
        "company_scoped": True,
        "ingestion_type": "snapshot",
        "cursor_field": None,
        "primary_keys": ["id"],
        "bc_table_id": None,
    },
    # -- standard endpoints: cdc_with_deletes ----------------------------------
    "generalLedgerAccounts": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 15,
    },
    "bankAccounts": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 270,
    },
    "companyInformation": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "contacts": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 5050,
    },
    "countriesRegions": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 9,
    },
    "currencies": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 4,
    },
    "currencyExchangeRates": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 330,
    },
    "customers": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 18,
    },
    "generalJournalBatches": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 232,
    },
    "reasonCodes": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 231,
    },
    "generalJournalLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 81,
    },
    "defaultDimensions": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 352,
    },
    "dimensionValues": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 349,
    },
    "dimensions": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 348,
    },
    "employees": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 5200,
    },
    "generalProductPostingGroups": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 251,
    },
    "vendors": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 23,
    },
    "inventoryPostingGroups": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 94,
    },
    "itemCategories": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 5722,
    },
    "itemVariants": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 5401,
    },
    "items": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 27,
    },
    "locations": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 14,
    },
    "opportunities": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 5092,
    },
    "paymentMethods": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 289,
    },
    "paymentTerms": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 3,
    },
    "purchaseLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 39,
    },
    "jobs": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 167,
    },
    "shipmentMethods": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 10,
    },
    "unitsOfMeasure": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 204,
    },
    "timeSheetDetails": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 953,
    },
    "salesHeaders": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 36,
    },
    "salesLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 37,
    },
    "purchaseHeaders": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "cdc_with_deletes",
        "cursor_field": "systemModifiedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": 38,
    },
    # -- standard endpoints: append (posted/immutable) -------------------------
    "generalLedgerEntries": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "itemLedgerEntries": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "purchaseReceiptLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "salesCreditMemoLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "purchaseReceiptHeaders": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "salesCreditMemoHeaders": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "salesShipmentLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "salesShipmentHeaders": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "postedGeneralJournalBatch": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "postedGeneralJournalLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "purchaseInvoiceHeaders": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "purchaseInvoiceLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "salesInvoiceHeaders": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "salesInvoiceLines": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "append",
        "cursor_field": "systemCreatedAt",
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    # -- standard endpoints: snapshot ------------------------------------------
    "rawCompanies": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "snapshot",
        "cursor_field": None,
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
    "dimensionSetEntries": {
        "api_group": "standardEndpoints",
        "company_scoped": True,
        "ingestion_type": "snapshot",
        "cursor_field": None,
        "primary_keys": ["systemId"],
        "bc_table_id": None,
    },
}

# OData EDM type -> Spark type mapping used for dynamic schema discovery
EDM_TYPE_MAP: dict[str, type] = {
    "Edm.String": StringType,
    "Edm.Guid": StringType,
    "Edm.Int32": LongType,
    "Edm.Int64": LongType,
    "Edm.Decimal": DecimalType,
    "Edm.Double": DecimalType,
    "Edm.Boolean": BooleanType,
    "Edm.Date": StringType,
    "Edm.DateTimeOffset": StringType,
    "Edm.Duration": StringType,
    "Edm.Stream": StringType,
    "Edm.Binary": StringType,
}

# Delete tracking schema (for the deletedRecords API page)
DELETED_RECORD_SCHEMA = StructType([
    StructField("entryNo", LongType(), nullable=False),
    StructField("tableId", LongType(), nullable=True),
    StructField("companyId", StringType(), nullable=True),
    StructField("deletedSystemId", StringType(), nullable=True),
    StructField("recordPosition", StringType(), nullable=True),
    StructField("deletedAt", StringType(), nullable=True),
    StructField("systemModifiedAtOriginal", StringType(), nullable=True),
    StructField("systemCreatedAt", StringType(), nullable=True),
    StructField("systemCreatedBy", StringType(), nullable=True),
    StructField("systemId", StringType(), nullable=True),
    StructField("systemModifiedAt", StringType(), nullable=True),
    StructField("systemModifiedBy", StringType(), nullable=True),
])

DELETE_TRACKER_SCHEMA = StructType([
    StructField("id", StringType(), nullable=True),
    StructField("tableId", LongType(), nullable=True),
    StructField("companyId", StringType(), nullable=True),
    StructField("recordsDeleted", LongType(), nullable=True),
    StructField("systemCreatedAt", StringType(), nullable=True),
    StructField("systemModifiedAt", StringType(), nullable=True),
    StructField("systemId", StringType(), nullable=True),
])
